### ISSUE TITLE
json psram failed

### ISSUE THREAD

**Issue by brannik** [linuxthor/My-TTGO-Watch#1]
Hello im trying to upload master branch on ttgo t-watch 2020. Without touching anything, code is uploaded but there is only black screen and this error - [E][json_psram_allocator.h:16] allocate(): allocate 0 bytes (0x0) json psram failed. Any advance how to make it work will be nice. Sory for my bad  english

**Comment by ipendle** [comment]
I also get the same outcome: black screen and un-responsive ttgo t-watch 2020 using the master branch. If I use sharandac/My-TTGO-Watch it works fine.

**Comment by brannik** [comment]
It works fine under linux owe reinstalled entire pc just to test and working fine with arduino ide under ubuntu

**Comment by ipendle** [comment]
I got it to build and run on my watch by taking the json_psram_allocator.h file from the main on sharandac/My-TTGO-Watch. They have have slightly different functions defined for allocate(). It is working perfectly for me now. I'm building on a Mac.

**Comment by linuxthor** [comment]
I am very grateful to @ipendle for troubleshooting this issue and have incorporated the fix described. Apologies for the delay - I had some very time consuming paid work here so have had zero spare time for fun stuff!
