### ISSUE TITLE
black screen, no response after flash (pio on win64) 

### ISSUE THREAD

**Issue by theycallmevirgo** [linuxthor/My-TTGO-Watch#4]
upload from pio successful; monitor returns

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:QIO, clock div:1
load:0x3fff0018,len:4
load:0xffffffff,len:-1
ets Jul 29 2019 12:21:46

**Comment by linguine2552** [comment]
I was able to reproduce the bug, looks like linuxthor is working on this project some more. I have an earlier fork that compiles and boots correctly, I'll upload it to my page in case you want it.

**Comment by theycallmevirgo** [comment]
> I was able to reproduce the bug, looks like linuxthor is working on this project some more. I have an earlier fork that compiles and boots correctly, I'll upload it to my page in case you want it.

Yes please :).

**Comment by linuxthor** [comment]
This should be fixed per the latest version
