### ISSUE TITLE
SSID Spam crashes

### ISSUE THREAD

**Issue by Crsarmv7l** [linuxthor/My-TTGO-Watch#5]
It appears the SSID Spam app (Wireless) makes the screen flicker and the watch restart.

There are also warnings of "ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]" on the rick SSIDs

**Comment by linuxthor** [comment]
Resolved with the latest commit - @Crsarmv7l please try once more and thanks for the report

**Comment by Crsarmv7l** [comment]
Cool appreciate the fix, as a side note I have gotten packet injection working on the t-watch on my fork. Might be something you would like to include in yours.

**Comment by linuxthor** [comment]
That looks great @Crsarmv7l. Very grateful for the suggestion. I'm spending a little time on stability and battery life at the moment then I will look to include more tools next.
