### ISSUE TITLE
https://github.com/sharandac/ESP-Mail-Client

### ISSUE THREAD

**Issue by reinethernal** [linuxthor/My-TTGO-Watch#6]
https://github.com/sharandac/ESP-Mail-Client repo is now not available.
Got to comment to start build process

**Comment by Crsarmv7l** [comment]
Replace with https://github.com/mobizt/ESP-Mail-Client.git#v2.4.8

You may also have problems with ESP8266Audio if so replace with earlephilhower/ESP8266Audio@1.9.5

**Comment by linuxthor** [comment]
Thanks for the information - update pushed
